version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-production
    image: onlycat.azurecr.io/onlycat-backend
    container_name: onlycat-backend
    restart: on-failure
    ports:
      - 5000:5000
    # volumes:
    #   - backend:/app
    depends_on:
      - mongodb
    networks:
      - onlycat
    command: node src/main.js

  frontend:
    build: ./frontend
    image: onlycat.azurecr.io/onlycat-frontend
    container_name: onlycat-frontend
    restart: on-failure
    domainname: "onlycat"
    ports:
      - 80:80
      - 443:443
    env_file: ./frontend/.env.production
    # volumes:
    #   - frontend:/app/build
    depends_on:
      - backend
    networks:
      - onlycat

  mongodb:
    image: mongo
    container_name: onlycat-mongodb
    restart: on-failure
    ports:
      - 27017:27017
    # volumes:
    #   - mongodb:/data/db
    #   - mongodb-config:/data/configdb
    networks:
      - onlycat

# volumes:
#   frontend:
#     driver: azure_file
#     driver_opts:
#       share_name: frontend
#       storage_account_name: onlycat
#   backend:
#     driver: azure_file
#     driver_opts:
#       share_name: backend
#       storage_account_name: onlycat
#   mongodb:
#     driver: azure_file
#     driver_opts:
#       share_name: mongodb
#       storage_account_name: onlycat
#   mongodb-config:
#     driver: azure_file
#     driver_opts:
#       share_name: mongodb-config
#       storage_account_name: onlycat

networks:
  onlycat:
    driver: bridge # default
