# for azure VM
version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: onlycat-mongodb
    restart: on-failure
    networks:
      - onlycat
    volumes:
      - ../deployment/db-data:/data/db

  backend:
    build: ./backend
    image: onlycat-backend
    container_name: onlycat-backend
    restart: on-failure
    depends_on:
      - mongodb
    networks:
      - onlycat

  frontend:
    build: ./frontend
    image: onlycat-frontend
    container_name: onlycat-frontend
    restart: on-failure
    domainname: "onlycat" ##
    depends_on:
      - backend
    ports:
      - 80:80
      - 443:443
    volumes:
      # - ../deployment/html:/usr/share/nginx/html
      - ../deployment/cert-conf:/etc/nginx/ssl
    networks:
      - onlycat

networks:
  onlycat:
    driver: bridge # default
