version: '3.8'
# azure auto expose port (or networks: work for me idk cause i work :P )
services:
  backend:
    build: ./backend
    image: onlycat.azurecr.io/onlycat-backend
    container_name: onlycat-backend
    restart: on-failure
    # ports:
    #   - 127.0.0.1:5000:5000
    # volumes:
    #   - backend:/app
    depends_on:
      - mongodb
    networks:
      - onlycat
    command: node src/main.js

  frontend:
    build: ./frontend
    image: onlycat.azurecr.io/onlycat-frontend
    container_name: onlycat-frontend
    restart: on-failure
    domainname: "onlycat"
    ports:
      - 80:80
      - 443:443
    # volumes:
    #   - frontend:/app/build
    depends_on:
      - backend
    networks:
      - onlycat

  mongodb:
    image: mongo
    container_name: onlycat-mongodb
    restart: on-failure
    networks:
      - onlycat
    volumes:
      - db-data:/db-data
    command: [ "mongod", "--dbpath=/db-data" ]
    # /data/db in azure wont work so change storage path

volumes:
  db-data:
    driver: azure_file
    driver_opts:
      share_name: mongodb-data
      storage_account_name: onlycat
#   frontend:
#     driver: azure_file
#     driver_opts:
#       share_name: frontend
#       storage_account_name: onlycat
#   backend:
#     driver: azure_file
#     driver_opts:
#       share_name: backend
#       storage_account_name: onlycat

networks:
  onlycat:
    driver: bridge # default
