# for azure VM
version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: onlycat-mongodb
    restart: on-failure
    networks:
      - onlycat
    volumes:
      - ../deployment/db-data:/data/db

  backend:
    build: ./backend
    image: onlycat-backend
    container_name: onlycat-backend
    restart: on-failure
    depends_on:
      - mongodb
    networks:
      - onlycat

  frontend:
    build: ./frontend
    image: onlycat-frontend
    container_name: onlycat-frontend
    restart: on-failure
    domainname: "onlycat" ##
    depends_on:
      - backend
    ports:
      - 80:80
      - 443:443
    volumes:
      - web-root:/usr/share/nginx/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    networks:
      - onlycat

  certbot:
    image: certbot/certbot
    container_name: onlycat-certbot
    volumes:
      - web-root:/usr/share/nginx/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - frontend

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/azureuser/only-cat-dcw/deployment/html/
      o: bind

networks:
  onlycat:
    driver: bridge # default
