version: '3.8'
services:
  backend:
    build: ./backend
    # image: onlycat.azurecr.io/onlycat-backend
    container_name: onlycat-backend
    restart: on-failure
    ports:
      - 5000:5000
    # volumes:
    #   - ./backend:/app
    depends_on:
      - mongodb
    networks:
      - onlycat
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: onlycat-frontend
    restart: on-failure
    ports:
      - 80:80
    # volumes:
    #   - ./frontend:/app/build
    depends_on:
      - backend
    networks:
      - onlycat

  mongodb:
    image: mongo
    container_name: onlycat-mongodb
    restart: on-failure
    # volumes:
    #   - mongodb:/data/db
    #   - mongodb-config:/data/configdb
    networks:
      - onlycat

# volumes:
#   mongodb:
#   mongodb-config:

networks:
  onlycat:
    driver: bridge # default
